spring:
  database.url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  h2.console.enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

message: Hello from application-local.yml configuration

server:
  port: 8081
